# Generated by Django 2.2.2 on 2019-06-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField(blank=True, default=None, null=True, verbose_name='Recorded Date')),
                ('channel', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Channel')),
                ('country', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Country Name')),
                ('os', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Channel')),
                ('impressions', models.IntegerField(blank=True, default=None, null=True)),
                ('clicks', models.IntegerField(blank=True, default=None, null=True)),
                ('installs', models.IntegerField(blank=True, default=None, null=True)),
                ('spend', models.FloatField(blank=True, default=None, null=True, verbose_name='Spend')),
                ('revenue', models.FloatField(blank=True, default=None, null=True, verbose_name='Revenue')),
            ],
        ),
    ]
